package dw.fdb.com.fdbapp.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CART.
 */
public class Cart {

    private Long id;
    /** Not-null value. */
    private String libelle_produit;
    private String description_short;
    private String description_longue;
    private String image_url;
    private Integer qte;
    private Double prix_ttc;
    private java.util.Date date_upd;
    private java.util.Date date_add;

    public Cart() {
    }

    public Cart(Long id) {
        this.id = id;
    }

    public Cart(Long id, String libelle_produit, String description_short, String description_longue, String image_url, Integer qte, Double prix_ttc, java.util.Date date_upd, java.util.Date date_add) {
        this.id = id;
        this.libelle_produit = libelle_produit;
        this.description_short = description_short;
        this.description_longue = description_longue;
        this.image_url = image_url;
        this.qte = qte;
        this.prix_ttc = prix_ttc;
        this.date_upd = date_upd;
        this.date_add = date_add;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getLibelle_produit() {
        return libelle_produit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLibelle_produit(String libelle_produit) {
        this.libelle_produit = libelle_produit;
    }

    public String getDescription_short() {
        return description_short;
    }

    public void setDescription_short(String description_short) {
        this.description_short = description_short;
    }

    public String getDescription_longue() {
        return description_longue;
    }

    public void setDescription_longue(String description_longue) {
        this.description_longue = description_longue;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public Integer getQte() {
        return qte;
    }

    public void setQte(Integer qte) {
        this.qte = qte;
    }

    public Double getPrix_ttc() {
        return prix_ttc;
    }

    public void setPrix_ttc(Double prix_ttc) {
        this.prix_ttc = prix_ttc;
    }

    public java.util.Date getDate_upd() {
        return date_upd;
    }

    public void setDate_upd(java.util.Date date_upd) {
        this.date_upd = date_upd;
    }

    public java.util.Date getDate_add() {
        return date_add;
    }

    public void setDate_add(java.util.Date date_add) {
        this.date_add = date_add;
    }

}
