package dw.fdb.com.fdbapp.db.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBCartDaoConfig;

    private final DBCartDao dBCartDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        dBCartDaoConfig = daoConfigMap.get(DBCartDao.class).clone();
        dBCartDaoConfig.initIdentityScope(type);

        dBCartDao = new DBCartDao(dBCartDaoConfig, this);

        registerDao(DBCart.class, dBCartDao);
    }

    public void clear() {
        dBCartDaoConfig.getIdentityScope().clear();
    }

    public DBCartDao getDBCartDao() {
        return dBCartDao;
    }

}
